name: multi_modular
packages:
  - core/**
  - features/**


command:
  bootstrap:
    environment:
      sdk: ^3.7.2
      flutter: ">=1.17.0"
      
  dependencies:
    dio: ^5.5.0

  dev_dependencies:
    flutter_lints: ^5.0.0